on:
  push:
    branches: [ master ]
jobs:
  apply:
    name: terraform apply
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: terraform init
        uses: hashicorp/terraform-github-actions@v1
        with:
          tf_actions_version: 0.12.20
          tf_actions_subcommand: 'init'
          tf_actions_working_dir: './'
          tf_actions_comment: true
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      # - name: terraform apply
      #   uses: hashicorp/terraform-github-actions@v1
      #   with:
      #     tf_actions_version: 0.12.20
      #     tf_actions_subcommand: 'apply'
      #     tf_actions_working_dir: './'
      #     tf_actions_comment: true
      #   env:
      #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
